# Brief file description
# Copyright (C) 2025  Arsen ArsenoviÄ‡ <aarsenovic8422rn@raf.rs>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


services:
  # User service and its state
  user_service:
    build:
      context: .
      dockerfile: docker/Dockerfile-java
      args:
        SERVICE: user-service
    ports:
      - "8080:8080"
    command:
      - /code/build/libs/user-service-0.0.1-SNAPSHOT.jar
      - --spring.profiles.active=dev,local
    depends_on:
      user_service_db:
        condition: service_healthy
      broker:
        condition: service_started
    volumes:
      - user_service_gradle:/home/service/.gradle
    post_start:
      - command: "chown -R service: /home/service/.gradle"
        user: root
    develop:
      watch:
        - action: sync+restart
          path: ./user-service/src
          target: /code/src
          ignore:
            - main/resources/db/migration
        - action: sync+restart
          path: ./user-service/build.gradle.kts
          target: /code/build.gradle.kts
        - action: sync+restart
          path: ./user-service/settings.gradle.kts
          target: /code/settings.gradle.kts

  user_service_db:
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: lmaolmao123
      POSTGRES_DB: user-service
      POSTGRES_USER: user-service
    volumes:
      - user_service_db_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d user-service -U user-service"
      interval: 3s
      start_period: 3s

  # Notification service and its state
  notification_service:
    build:
      context: .
      dockerfile: docker/Dockerfile-java
      args:
        SERVICE: notification-service
    command:
      - /code/build/libs/notification-service-0.0.1-SNAPSHOT.jar
      - --spring.profiles.active=dev,local
    depends_on:
      # notification_service_db:
      #   condition: service_healthy
      broker:
        condition: service_started
    volumes:
      - notification_service_gradle:/home/service/.gradle
    post_start:
      - command: "chown -R service: /home/service/.gradle"
        user: root
    develop:
      watch:
        - action: sync+restart
          path: ./notification-service/src
          target: /code/src
          ignore:
            - main/resources/db/migration
        - action: sync+restart
          path: ./notification-service/build.gradle.kts
          target: /code/build.gradle.kts
        - action: sync+restart
          path: ./notification-service/settings.gradle.kts
          target: /code/settings.gradle.kts

  # notification_service_db:
  #   image: postgres:17
  #   restart: unless-stopped
  #   shm_size: 128mb
  #   environment:
  #     POSTGRES_PASSWORD: lmaolmao123
  #     POSTGRES_DB: notification-service
  #     POSTGRES_USER: notification-service
  #   volumes:
  #     - notification_service_db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: "pg_isready -d notification-service -U notification-service"
  #     interval: 3s
  #     start_period: 3s

  # Central message broker.  The version below provides the management
  # interface to ease development.  Uses default credentials of guest / guest.
  # Good enough for dev.
  broker:
    image: rabbitmq:4.0-management
    ports:
      # Management interface.
      - "15672:15672"

volumes:
  user_service_gradle:
  notification_service_gradle:
  # Database storage persistence.
  # notification_service_db_data:
  user_service_db_data:
